description: "Let's vibe \U0001F680"
name: devopsdaysdc25
origin:
  generated: true
  template:
    branch: main
    commit hash: 2bb896090549aec15df0859464174987eb2ca25e
    cookiecutter:
      _checkout: null
      _repo_dir: /Users/jonzeolla/.cookiecutters/ai-native-python
      _template: gh:zenable-io/ai-native-python
      company_domain: jonzeolla.com
      company_name: jonzeolla
      dockerhub: 'yes'
      github_org: jonzeolla
      license: MIT
      project_name: devopsdaysdc25
      project_owner_github_username: jonzeolla
      project_short_description: "Let's vibe \U0001F680"
      project_slug: devopsdaysdc25
      public: 'yes'
      python_version: '3.13'
    dirty: false
    location: https://github.com/zenable-io/ai-native-python.git
  timestamp: '2025-09-18T15:36:31+00:00'
